#!/bin/sh

# Packages for generating the UKI and optional initrd.
# 
# This can be used to create a standalone signer/builder - but 
# for now moving it back to the sidecar, simpler.
# 
# To check: gzip -dc ../initos-initrd.img | cpio -idmv
add_signer() {
  apk add  \
    efi-mkkeys sbsigntool \
    mkinitfs binutils  \
    zstd tar e2fsprogs libarchive \
     uuidgen openssh \
     squashfs-tools cryptsetup dosfstools eudev minisign
      
  # tar - required for multiple -C for creating the sqfs.
  # libarchive - optional dep of mk2efs

  # No longer used: efi-mkuki (forked, upstream no longer works - systemd )
  # gummiboot - forked 


  # Udev used in initrd
  
  echo 'disable_trigger=yes' >> /etc/mkinitfs/mkinitfs.conf

  if [ -f /initrd/bin/busybox ]; then
    ls -l /initrd/bin
    (chroot /initrd /bin/busybox --install -s /bin)
  fi

}


"$@"