name: uki-stub
on:
  push: {}

jobs:
  build-docker:
    name: Build-in-docker
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: https://ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: stub binary
        uses: docker/build-push-action@v6
        with:
          target: out
          push: true
          tags: ghcr.io/costinm/uki-stub/uki-stub:latest

      - name: stub binary
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ghcr.io/costinm/uki-stub/uki-signer:latest


